project_id = "osyiefnrrvrouzzsaspi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[functions.process-payslip-ocr]
verify_jwt = true

[functions.send-invite]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
